### ISSUE TITLE
test_delaunay_reduce test failed with Python-3.6

### ISSUE THREAD

**Issue by sagitter** [atztogo/spglib#34]
Hi all.

`test_delaunay_reduce` is failing with Python-3.6:

```
+ nosetests-3.6 -v
test_get_symmetry_anti_ferro (test_collinear_spin.TestGetSymmetry) ... ok
test_get_symmetry_broken_magmoms (test_collinear_spin.TestGetSymmetry) ... ok
test_get_symmetry_ferro (test_collinear_spin.TestGetSymmetry) ... ok
test_get_hall_number_from_symmetry (test_hall_number_from_symmetry.TestGetHallNumberFromSymmetry) ... ok
test_delaunay_reduce (test_niggli_delaunay.TestNiggliDelaunay) ... FAIL
test_niggli_angles (test_niggli_delaunay.TestNiggliDelaunay) ... ok
test_niggli_reduce (test_niggli_delaunay.TestNiggliDelaunay) ... ok
test_get_ir_reciprocal_mesh (test_reciprocal_mesh.TestReciprocalMesh) ... ok
test_get_stabilized_reciprocal_mesh (test_reciprocal_mesh.TestReciprocalMesh) ... ok
test_find_primitive (test_spglib.TestSpglib) ... ok
test_get_symmetry (test_spglib.TestSpglib) ... ok
test_get_symmetry_dataset (test_spglib.TestSpglib) ... ok
test_refine_cell (test_spglib.TestSpglib) ... ok
======================================================================
FAIL: test_delaunay_reduce (test_niggli_delaunay.TestNiggliDelaunay)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/spglib-1.9.9/python/test/test_niggli_delaunay.py", line 40, in test_delaunay_reduce
    self._reduce(delaunay_reduce, self._delaunay_lattices)
  File "/builddir/build/BUILD/spglib-1.9.9/python/test/test_niggli_delaunay.py", line 63, in _reduce
    " angles: %s" % np.array(get_angles(reduced_lattice))]))
AssertionError: False is not true : # 64
Input lattice
[[ 15.9359925    0.           0.        ]
 [ -7.96799625  13.80097434   0.        ]
 [  0.           0.           3.89199817]]
 angles: [  90.   90.  120.]
Reduced lattice in reference data
[[  0.           0.           3.89199817]
 [ 15.9359925    0.           0.        ]
 [ -7.96799625  13.80097434   0.        ]]
 angles: [ 120.   90.   90.]
Reduced lattice
[[ -0.          -0.          -3.89199817]
 [  7.96799625 -13.80097434  -0.        ]
 [-15.9359925   -0.          -0.        ]]
 angles: [ 120.   90.   90.]
----------------------------------------------------------------------
Ran 13 tests in 33.756s
FAILED (failures=1)
```

**Comment by atztogo** [comment]
Thanks @sagitter. Delaunay reduced cell is sometimes sensitive to last digits of floating point values, therefore it can depend on system. However this failed test should pass in the sense of the Delaunay reduction algorithm. So my assertion was wrong. I fixed test_niggli_delaunay to compare between metric tensors rather than between basis vectors. This fix was merged it to the develop and master branches.

**Comment by sagitter** [comment]
`spglib` updated to https://github.com/atztogo/spglib/commit/bf4b4c7b87e77abd709fe2d93ade8a4f5981f989

```
+ nosetests-3.6 -v
Python detected LC_CTYPE=C: LC_ALL & LANG coerced to C.UTF-8 (set another locale or PYTHONCOERCECLOCALE=0 to disable this locale coercion behaviour).
test_get_symmetry_anti_ferro (test_collinear_spin.TestGetSymmetry) ... ok
test_get_symmetry_broken_magmoms (test_collinear_spin.TestGetSymmetry) ... ok
test_get_symmetry_ferro (test_collinear_spin.TestGetSymmetry) ... ok
test_get_hall_number_from_symmetry (test_hall_number_from_symmetry.TestGetHallNumberFromSymmetry) ... ok
test_delaunay_reduce (test_niggli_delaunay.TestNiggliDelaunay) ... FAIL
test_niggli_angles (test_niggli_delaunay.TestNiggliDelaunay) ... ok
test_niggli_reduce (test_niggli_delaunay.TestNiggliDelaunay) ... ok
test_get_ir_reciprocal_mesh (test_reciprocal_mesh.TestReciprocalMesh) ... ok
test_get_ir_reciprocal_mesh_distortion (test_reciprocal_mesh.TestReciprocalMesh) ... ok
test_get_stabilized_reciprocal_mesh (test_reciprocal_mesh.TestReciprocalMesh) ... ok
test_find_primitive (test_spglib.TestSpglib) ... ok
test_get_symmetry (test_spglib.TestSpglib) ... ok
test_get_symmetry_dataset (test_spglib.TestSpglib) ... ok
test_refine_cell (test_spglib.TestSpglib) ... ok
======================================================================
FAIL: test_delaunay_reduce (test_niggli_delaunay.TestNiggliDelaunay)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/spglib-bf4b4c7b87e77abd709fe2d93ade8a4f5981f989/python/test/test_niggli_delaunay.py", line 40, in test_delaunay_reduce
    self._reduce(delaunay_reduce, self._delaunay_lattices)
  File "/builddir/build/BUILD/spglib-bf4b4c7b87e77abd709fe2d93ade8a4f5981f989/python/test/test_niggli_delaunay.py", line 64, in _reduce
    " angles: %s" % np.array(get_angles(reduced_lattice))]))
AssertionError: False is not true : # 106
Input lattice
[[ 11.2569947    0.           0.        ]
 [ -5.62849735   9.74884338   0.        ]
 [  0.           0.           5.85299725]]
 angles: [  90.   90.  120.]
Reduced lattice in reference data
[[  0.           0.           5.85299725]
 [ 11.2569947    0.           0.        ]
 [ -5.62849735   9.74884338   0.        ]]
 angles: [ 120.   90.   90.]
Reduced lattice
[[  0.           0.           5.85299725]
 [ 11.2569947    0.           0.        ]
 [  5.62849735   9.74884338   0.        ]]
 angles: [ 60.  90.  90.]
----------------------------------------------------------------------
Ran 14 tests in 43.969s
FAILED (failures=1)
```

**Comment by atztogo** [comment]
Thanks @sagitter. Delaunay reduction implementation may have a problem. I will have a look into the detail.

**Comment by sagitter** [comment]
The test fails on `i386` architecture only.

**Comment by atztogo** [comment]
I modified delaunay.c to be less sensitive to tiny numerical difference. I tested this on an i386 virtual machine and it seems working. I merged this change to master and develop branches.

**Comment by sagitter** [comment]
Test ran correctly on all architectures.
Thank you.
